apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: team9-api-tls
  namespace: backend
spec:
  secretName: team9-api-tls
  dnsNames:
    - api.team9.cloud.skala-ai.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
