apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - envoyproxy.yaml
  - gateway.yaml
  - public-routes.yaml
  - protected-routes.yaml
  - protected-route-security-policy.yaml
