apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: team9-protected-route-auth
  namespace: backend
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: team9-protected-routes
  extAuth:
    headersToExtAuth:
      - authorization
      - cookie
      - origin
    http:
      backendRefs:
        - name: backend-auth-service
          port: 8088
      path: /authorize
      headersToBackend:
        - x-auth-gateway
        - x-cognito-sub
        - x-user-id
        - x-user-name
        - x-user-email
