{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ default (printf "%s-secret" (include "backend-dev.fullname" .)) .Values.externalSecret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backend-dev.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.clusterSecretStoreName }}
  target:
    name: {{ default (printf "%s-secret" (include "backend-dev.fullname" .)) .Values.externalSecret.targetName }}
    creationPolicy: Owner
  {{- if .Values.externalSecret.data }}
  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- with .remoteRef.property }}
        property: {{ . }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.externalSecret.remoteKey }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.remoteKey }}
  {{- end }}
{{- end }}
