namespace: frontend

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/team9-frontend
  tag: latest
  pullPolicy: IfNotPresent

podAnnotations: {}

podLabels: {}

service:
  type: ClusterIP
  port: 80

containerPort: 80

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: front.team9.cloud.skala-ai.com
  hosts:
    - host: front.team9.cloud.skala-ai.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  - name: NODE_ENV
    value: development

envFromSecretRefs:
  - frontend-app-secret

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
